#!/usr/bin/env ruby

def password(length)
  abc = [('a'..'z').to_a, ('A'..'Z').to_a, ('0'..'9').to_a, "!\"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~".chars]
  loop do
    input = ''
    length.times { input << abc.join[rand(abc.join.length)] }
    output = input.chars
    if (output & abc[0]).any? && (output & abc[1]).any? && (output & abc[2]).any? && (output & abc[3]).any?
      return output.join
      break
    end
  end
end

class String
  def style_success; "\033[2m\033[100m#{self}\033[0m" end
  def style_error; "\033[2m#{self}\033[0m" end
end

if ARGV.length != 0
  case ARGV[0].to_i
  when 4..64
    puts password(ARGV[0].to_i).style_success
  else
    puts 'Invalid argument. Enter a value between 4 and 64.'.style_error
  end
else
  puts password(8).style_success
end
