#!/usr/bin/env ruby

def password(length)
  abc = ['abcdefghijklmnopqrstuvwxyz'.chars, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.chars, '0123456789'.chars, "!\"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~".chars]
  abc_ = abc.join
  loop do
    input = ''
    length.times do
      input << abc_[rand(abc_.length)]
    end
    output = input.chars
    if (output & abc[0]).any? && (output & abc[1]).any? && (output & abc[2]).any? && (output & abc[3]).any?
      return output.join
      break
    end
  end
end

class String
  def style_success; "\033[90m\033[100m#{self}\033[0m" end
  def style_error; "\033[2m#{self}\033[0m" end
end

if ARGV.length != 0
  case ARGV[0].to_i
  when 4...65
    puts password(ARGV[0].to_i).style_success
  else
    puts 'Invalid argument. Enter a value between 4 and 64.'.style_error
  end
else
  puts password(8).style_success
end
